---
name: Manually build a release

on:
  workflow_dispatch:
jobs:
  build:
    name: Build Packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: Windows
            ARCHITECTURE: x64
            BUILD_CMD: ci/build.ps1
            PACKAGE_CMD: ci/package.ps1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python for ${{matrix.target}}
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies for ${{matrix.target}}
        run: |
          pip install pyinstaller websockets bleak requests winrt-Windows.Foundation.Collections
          pushd ui && npm install && popd
      - name: Build application for ${{matrix.target}}
        run: ${{ matrix.BUILD_CMD }}
      - name: Package application for ${{matrix.TARGET}}
        id: package-app
        run: |
          ${{ matrix.PACKAGE_CMD }} "${{needs.create-release.outputs.name}}-${{matrix.TARGET}}-${{matrix.ARCHITECTURE}}-${{needs.create-release.outputs.tag}}"
      - name: Upload release asset for ${{matrix.target}}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.release_url}}
          asset_path: ${{ steps.package-app.outputs.asset_path }}
          asset_name: ${{ steps.package-app.outputs.asset_name }}
          asset_content_type: application/zip
